### ISSUE TITLE
Search, podrobnosti knjige

### ISSUE THREAD

**Issue by katykro** [aniiiim/Najbolje-ocenjene-knjige#3]
Pri zaključevanju projekta Najbolje ocenjene knjige pri predmetu Osnove podatkovnih baz smo naletele na nekaj težav, in sicer:
- Search nam na začetni strani ne dela. Funkcijo potrebno za izvedbo ukaza v search-u smo definirale v spletna stran.py pod funkcijo
@get('/books')
def index():
in v template-u index.html

- Ko kliknemo na želeno knjigo, da bi videli več informacij o knjigi nam template ne naloži v celoti in s tem ne moremo urejati te strani. Ta del je definiran kot
@get("/item/<book_id>/")
def item_get(book_id):
     return template('product_details.html')

Ta funkcija naj bi nam vrnila template product_details.html, vendar ga ne naloži celotnega. Zanimivo je, da če pa isti template kličemo s funkcijo:
@get('/product_details.html')
def podrobnosti():
    return template('product_details.html')
pa ta funkcija deluje.

**Comment by MarvinHerzog** [comment]
- Glede search vam predlagam, da naredite redirect na `/all` z izbrano poizvedbijo, saj se tam nahajajo vse knjige in ne le izbor najboljših. Pri tem izbrišite tisti del z `%` python ukazi in v `form` značko dodajte `form action="/all"`. Ko bo stran `/all` delovala lahko nato tam usposobimo search.

- Če prav razumem vas moti to, da ne naloži slik, stila strani ter javascripta. Problem je v tem, da imate v `.html` datotekah drugače kot v Pythonu definirano lokacijo vaših statičnih datotek (čudi me, da vam jih naloži na ostalih straneh - meni jih namreč ne). Kot primer poglejte glavo `product_details.html`:

```
    <!-- Bootstrap styles -->
    <link href="assets/css/bootstrap.css" rel="stylesheet"/>
    <!-- Customize styles -->
    <link href="style.css" rel="stylesheet"/>
    <!-- font awesome styles -->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet">
```
Ko naložite stran kakšnje knjige, dobi Python takšne `GET` zahteve:

```
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/ HTTP/1.1" 200 7774
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/assets/css/bootstrap.css HTTP/1.1" 404 788
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/style.css HTTP/1.1" 404 758
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/assets/font-awesome/css/font-awesome.css HTTP/1.1" 404 820
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/assets/js/jquery.js HTTP/1.1" 404 778
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/assets/js/bootstrap.min.js HTTP/1.1" 404 792
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/assets/img/a.jpg HTTP/1.1" 404 772
127.0.0.1 - - [21/Aug/2018 12:30:32] "GET /item/3628/assets/img/5.png HTTP/1.1" 404 772
```
Bodite pozorni na predzadnjo številko. Te označujejo [stanje HTTP odziva](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). Npr. `200` pomeni da je vse OK. `404` pomeni, da vaš zahtevek ni bil najden (kar se vam trenutno dogaja pri vseh statičnih datotekah). To je zato, ker imate v Pythonu pot do statičnih datotek definirano tako:

```
@route('/static/<filename:path>')
def static(filename):
    """Splošna funkcija, ki servira vse statične datoteke iz naslova
       /static/..."""
    return static_file(filename, root=static_dir)
```
Želite torej, da bi dobivale zahtevke za statične datoteke v obliki `GET /static/css/bootstrap.css` ipd. Morda vam bo najlažje, da uporabite _find and replace_ po vseh HTML datotekah in spremenite vsak `assets/` v `/static/`. Začetna poševnica poskrbi za to, da vam v GET zahtevku ne doda podstrani na začetek naslova (torej namesto `GET /item/3628/static/css/bootstrap.css` boste dobili `GET /static/css/bootstrap.css`) - to je verjetno tudi razlog zakaj vam CSS pri `@get('/product_details.html')` deluje. Nato preverite, ali se v Python shellu še pojavlja kak `404` (morda pri `style.css`, ki ga zaenkrat niste premaknile iz mape `shop-cart`).

**Comment by aniiiim** [comment]
- Za search smo naredile redirect na stran /all  in smo poskušale na strani /all filtrirat iskane knjige, vendar nam ne deluje.
-S stranjo product_details.html pa smo odpravile vse težave.

**Comment by MarvinHerzog** [comment]
Trenutno imate v bazi dve tabeli, `books` in `knjige`, ki sta identični. V pythonu enkrat kličete eno, drugič drugo. Najbolje, da se odločite za eno tabelo in drugo odstranite.

Search vam ne deluje, ker v `return template` podajate seznam z imenom `vse`, ne pa `predmeti`, kot ste ga definirale spodaj. Če združim obe poizvedbi, zadeva deluje:

```
    ORstring='''SELECT authors, title, average_rating, image_url, book_id FROM books
                WHERE 1=1\n'''
    parameters=[]
    try:
        krnekaj= query['search']
    except:
        query['search']=''    
    if query['search'] != '': 
        ORstring += '''AND (LOWER(title) LIKE LOWER(%s)\n'''
        parameters = parameters + ['%'+query['search']+'%'] 
    ORstring += ") ORDER BY title ASC" #po abecednem redu razvrščeni
    cur.execute(ORstring,parameters)
    predmeti=cur.fetchall()
```
Znotraj `return template` pa spremenite `vse=vse` v `vse=predmeti`.

**Comment by aniiiim** [comment]
Hvala za pomoč, zdaj deluje!
