### ISSUE TITLE
Tabela book_tags, books na več strani

### ISSUE THREAD

**Issue by katykro** [aniiiim/Najbolje-ocenjene-knjige#4]
Pri zaključevanju projekta Najbolje ocenjene knjige pri predmetu Osnove podatkovnih baz smo naletele na nekaj težav, in sicer:
- Tabelo book_tags nam ne uvozi pravilno in sicer nam cel stolpec goodreads_book_id da na NULL. Funkcija za ustvarjanje tabele in uvoz podatkov je definirana v books.py pod funkcijama ustvari_book_tags() in uvozi_book_tags(). Ker potrebujemo to tabelo povezati s tabelo books, smo poskušale noter definirati še stolpec book_tags_id SERIAL PRIMARY KEY, vendar se tabela tako uvaža še par ur več in na koncu pride napaka, da je nekaj prekinilo povezavo. Poskušale smo tudi z ALTER TABLE in deluje, vendar je goodreads_book_id še vedno na NULL. Sedaj nalagamo staro verzijo tabele book_tags, da se bo videlo, kaj nam dela težave. Mogoče bo trajalo nekaj ur, da jo naloži, saj je zelo velika tabela.

- Tabelo book_tags in books moramo povezati med sabo. To smo poskušale narediti na veliko manjših tabelah in nam je uspelo. SQL stavki so napisani v book in book_tags skupaj.py. Zanima nas, če je to v redu in če bo delovalo, če bomo to uporabili na večjih tabelah (ko enkrat dela goodreads_book_id).

- Na naši spletni strani bi rade books razdelile na več strani, saj nam drugače preveč dolgo nalaga stran. Poskušale smo to narediti, vendar ne deluje. Definirano je v spletna stran.py pod funkcijo
@get('/all')
def products():
in v template-u four-col.html.

Že vnaprej se zahvaljujemo za odgovore.

**Comment by MarvinHerzog** [comment]
- V _uvozi_book_tags()_ spremenite `r= r[1:(len(r))]` v `r= r[0:(len(r))]`, sicer vam manjka prvi stolpec (`goodreads_book_id`).

- Sicer nimam dostopa do testnih tabel, vendar zgleda, kot da bi moralo delovati. Vam pa zaradi velikosti tabele odsvetujem, da delate pogled. Najbolje, da uporabite join med tags - book_tags - books takrat, ko jih zares potrebujete, npr. na strani posamezne knjige (kjer izpišete vse njene tags), ali ko filtrirate knjige po izbranem tag-u.

- `/all` mi trenutno ne deluje, saj dobim napako
```
  File "C:\Users\Marvin\Desktop\Najbolje-ocenjene-knjige-master\views\four-col.html", line 104, in <module>
    %pic = slike[vse[i-1][0]]
KeyError: 'Patricia Schultz'
```
Namreč, prvi element posamezne vrstice od `vse` (se pravi: `vse[i-1][0]`) je ime avtorja, ne book_id kot bi ga potrebovale za slovar `slike`. V resnici ne razumem zakaj potrebujete dve SQL poizvedbi, saj je četrti element vrstice v `vse` že kar URL slike. Predlagam, da ju kar združite.

Verjetno boste še morale spodaj popraviti  `{{i[1]}} v` `{{vse[i][1]}}`. Ko bo vam stran delala, pushajte stvar na GitHub, pa bomo rešili še z delitvijo na strani.

- Mimogrede, dajte uporabniku _javnost_ še (ustrezno omejene) pravice za uporabo vaše strani, nato zamenjajte `import auth` z `import auth_public as auth`.

**Comment by MarvinHerzog** [comment]
Zdaj ko `/all` deluje sem še enkrat preletel številčenje strani.

V _four-col.html_ pri gumbih za strani odstranite pike na začetku vseh linkov, tj.

```
<li><a href=".?{{qstring}}&page={{pagenr-1}}">&laquo;</a></li>
```
v
```
<li><a href="?{{qstring}}&page={{pagenr-1}}">&laquo;</a></li>
```
Tako zadeva sicer deluje, vendar se v URL včasih pojavljajo nepotrebni znaki (skok iz strani 1 na 380 in spet na 1). To lahko popravite tako, da v Pythonu spremenite del z regularnim izrazom:

```
qstring = re.sub('&?page=\d','', qstring, flags=re.IGNORECASE)
```
v
```
qstring = re.sub('&?page=\d+','', qstring, flags=re.IGNORECASE)
```

**Comment by katykro** [comment]
Najlepša hvala za pomoč. Zanima me samo še, če se mogoče da popraviti, da številčenje strani ne pride v stolpcu, ampak v vrstici.

**Comment by MarvinHerzog** [comment]
Odstranite `<li>` značke pri številčenju.

**Comment by katykro** [comment]
Hvala za pomoč, sedaj vse deluje.
